"""
Atlas AI - Strategy Generation Endpoint
Converts natural language to trading strategy code using Claude
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import anthropic
import os
import json
import re

router = APIRouter(prefix="/atlas", tags=["atlas"])

# Initialize Anthropic client
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY')

class StrategyRequest(BaseModel):
    message: str
    name: str = ""

class StrategyResponse(BaseModel):
    success: bool
    name: str
    description: str
    code: str
    metrics: dict
    error: str = None

SYSTEM_PROMPT = """You are Atlas, an AI trading strategy generator for Stratify. Convert natural language trading ideas into Python strategy code.

OUTPUT FORMAT (JSON only, no markdown, no explanation):
{
  "name": "Strategy Name",
  "description": "One sentence summary",
  "code": "# Full Python strategy code here",
  "metrics": {
    "winRate": "estimated win rate like 65.5",
    "profitFactor": "estimated like 1.85",
    "sharpeRatio": "estimated like 1.42",
    "maxDrawdown": "estimated like 12.5"
  }
}

CODE TEMPLATE - Always use this structure:
```python
# [Strategy Name]
# Generated by Stratify AI

from stratify import Strategy

class [StrategyClassName](Strategy):
    def __init__(self):
        # Define parameters
        self.param = value
    
    def on_bar(self, bar):
        # Strategy logic using:
        # - self.indicators.RSI(period)
        # - self.indicators.SMA(period)
        # - self.indicators.EMA(period)
        # - self.indicators.MACD(fast, slow, signal)
        # - self.indicators.ATR(period)
        # - self.indicators.BBANDS(period, std)
        # - self.buy(size=position_size)
        # - self.sell()
        # - self.set_stop_loss(percent)
        # - self.set_trailing_stop(amount)
        pass
```

RULES:
1. Output ONLY valid JSON - no markdown code blocks, no explanation
2. Generate realistic but slightly optimistic metrics
3. Include proper risk management (stop loss, position sizing)
4. Use clear variable names and comments
5. Handle common indicators: RSI, MACD, SMA, EMA, ATR, Bollinger Bands"""


@router.post("/generate", response_model=StrategyResponse)
async def generate_strategy(request: StrategyRequest):
    """Generate a trading strategy from natural language description"""
    
    if not ANTHROPIC_API_KEY:
        raise HTTPException(status_code=500, detail="Anthropic API key not configured")
    
    if not request.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty")
    
    try:
        client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
        
        user_message = request.message
        if request.name:
            user_message += f"\n\nStrategy name: {request.name}"
        
        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=2048,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_message}]
        )
        
        response_text = message.content[0].text.strip()
        
        # Parse JSON response
        try:
            result = json.loads(response_text)
        except json.JSONDecodeError:
            # Try to extract JSON from response
            json_match = re.search(r'\{.*\}', response_text, re.DOTALL)
            if json_match:
                result = json.loads(json_match.group())
            else:
                raise HTTPException(status_code=500, detail="Failed to parse AI response")
        
        return StrategyResponse(
            success=True,
            name=result.get('name', request.name or 'Custom Strategy'),
            description=result.get('description', request.message[:100]),
            code=result.get('code', '# Error generating code'),
            metrics=result.get('metrics', {
                'winRate': '50.0',
                'profitFactor': '1.0',
                'sharpeRatio': '0.5',
                'maxDrawdown': '20.0'
            })
        )
        
    except anthropic.APIError as e:
        raise HTTPException(status_code=500, detail=f"Claude API error: {str(e)}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error: {str(e)}")


@router.get("/health")
async def atlas_health():
    """Health check for Atlas service"""
    return {
        "service": "atlas",
        "status": "ok" if ANTHROPIC_API_KEY else "missing_api_key",
        "model": "claude-sonnet-4-20250514"
    }
