import { useState, useRef, useEffect } from 'react';

// Claude spark icon (outlined)
const ClaudeIcon = ({ className }) => (
  <svg className={className} viewBox="0 0 24 24" fill="none">
    <path d="M12 2L15 9L22 12L15 15L12 22L9 15L2 12L9 9L12 2Z" stroke="#f97316" strokeWidth="1.5" strokeLinejoin="round" fill="none"/>
  </svg>
);

// Standard Mouse Arrow Cursor Component
const AnimatedCursor = ({ phase, target = 'submit' }) => {
  const isSubmit = target === 'submit' && (phase === 'cursor-submit' || phase === 'clicking-submit');
  const isAdd = target === 'add' && (phase === 'cursor-add' || phase === 'clicking-add');
  
  if (!isSubmit && !isAdd) return null;
  
  const isMoving = phase === 'cursor-submit' || phase === 'cursor-add';
  const isClicking = phase === 'clicking-submit' || phase === 'clicking-add';
  
  const duration = target === 'submit' ? 'duration-[2000ms]' : 'duration-[1500ms]';
  
  return (
    <div 
      className={`absolute z-50 pointer-events-none transition-all ${
        isMoving ? `${duration} ease-in-out` : 'duration-150'
      }`}
      style={{
        top: isMoving ? '-30px' : '4px',
        left: isMoving ? '20%' : '50%',
        transform: isClicking ? 'scale(0.9)' : 'scale(1)',
      }}
    >
      <svg 
        width="24" 
        height="24" 
        viewBox="0 0 24 24" 
        fill="none"
        className={`drop-shadow-xl transition-transform duration-100 ${isClicking ? 'translate-y-0.5' : ''}`}
      >
        {/* Standard mouse arrow cursor */}
        <path 
          d="M5.5 3.21V20.8c0 .45.54.67.85.35l4.86-4.86a.5.5 0 0 1 .35-.15h6.87c.48 0 .72-.58.38-.92L6.35 2.85a.5.5 0 0 0-.85.36Z"
          fill="white"
          stroke="#000"
          strokeWidth="1.5"
        />
      </svg>
      {/* Click ripple effect */}
      {isClicking && (
        <div className={`absolute top-2 left-1 w-4 h-4 rounded-full animate-ping ${
          target === 'add' ? 'bg-emerald-400/60' : 'bg-orange-400/60'
        }`} />
      )}
    </div>
  );
};

// 5 Demo Strategies
const demoStrategies = [
  {
    userMessage: "Buy TSLA when RSI drops below 30 and sell when it goes above 70. Use 2% position size with a 5% stop loss.",
    claudeResponse: "I've created an RSI Reversal Strategy based on your description:",
    code: `# RSI Reversal Strategy
# Generated by Stratify AI

from stratify import Strategy

class RSIStrategy(Strategy):
    def __init__(self):
        self.rsi_period = 14
        self.oversold = 30
        self.overbought = 70
        self.position_size = 0.02
        self.stop_loss = 0.05

    def on_bar(self, bar):
        rsi = self.indicators.RSI(self.rsi_period)

        if rsi < self.oversold:
            self.buy(size=self.position_size)
        elif rsi > self.overbought:
            self.sell()`,
    name: 'RSI Reversal Strategy',
    metrics: { winRate: '67.3', profitFactor: '1.92', sharpeRatio: '1.84', maxDrawdown: '12.4' }
  },
  {
    userMessage: "Create a golden cross strategy for AAPL. Buy when 50-day MA crosses above 200-day MA, sell on death cross. Risk 3% per trade.",
    claudeResponse: "I've built a Golden Cross Strategy for moving average crossovers:",
    code: `# Golden Cross Strategy
# Generated by Stratify AI

from stratify import Strategy

class GoldenCross(Strategy):
    def __init__(self):
        self.fast_period = 50
        self.slow_period = 200
        self.position_size = 0.03

    def on_bar(self, bar):
        fast_ma = self.indicators.SMA(self.fast_period)
        slow_ma = self.indicators.SMA(self.slow_period)
        prev_fast = self.indicators.SMA(self.fast_period, 1)
        prev_slow = self.indicators.SMA(self.slow_period, 1)

        if prev_fast < prev_slow and fast_ma > slow_ma:
            self.buy(size=self.position_size)
        elif prev_fast > prev_slow and fast_ma < slow_ma:
            self.sell()`,
    name: 'Golden Cross Strategy',
    metrics: { winRate: '58.2', profitFactor: '2.14', sharpeRatio: '1.56', maxDrawdown: '18.7' }
  },
  {
    userMessage: "Build a breakout strategy for NVDA. Enter long when price breaks above the 20-day high with volume 50% above average. Trail stop at 2 ATR.",
    claudeResponse: "I've created a Volume Breakout Strategy with ATR trailing stops:",
    code: `# Volume Breakout Strategy
# Generated by Stratify AI

from stratify import Strategy

class VolumeBreakout(Strategy):
    def __init__(self):
        self.lookback = 20
        self.volume_threshold = 1.5
        self.atr_multiplier = 2.0

    def on_bar(self, bar):
        high_20 = self.indicators.highest(self.lookback)
        avg_volume = self.indicators.SMA_volume(self.lookback)
        atr = self.indicators.ATR(14)

        if bar.close > high_20 and bar.volume > avg_volume * self.volume_threshold:
            self.buy()
            self.set_trailing_stop(atr * self.atr_multiplier)

        if self.position:
            self.update_trailing_stop(atr * self.atr_multiplier)`,
    name: 'Volume Breakout Strategy',
    metrics: { winRate: '52.8', profitFactor: '2.67', sharpeRatio: '2.01', maxDrawdown: '15.3' }
  },
  {
    userMessage: "MACD momentum strategy for SPY. Buy when MACD crosses above signal line and both are below zero. Sell when MACD crosses below signal. 5% position size.",
    claudeResponse: "I've built a MACD Momentum Strategy optimized for trend reversals:",
    code: `# MACD Momentum Strategy
# Generated by Stratify AI

from stratify import Strategy

class MACDMomentum(Strategy):
    def __init__(self):
        self.fast = 12
        self.slow = 26
        self.signal = 9
        self.position_size = 0.05

    def on_bar(self, bar):
        macd = self.indicators.MACD(self.fast, self.slow, self.signal)
        macd_line = macd['macd']
        signal_line = macd['signal']
        prev_macd = macd['prev_macd']
        prev_signal = macd['prev_signal']

        if prev_macd < prev_signal and macd_line > signal_line:
            if macd_line < 0:
                self.buy(size=self.position_size)
        elif prev_macd > prev_signal and macd_line < signal_line:
            self.sell()`,
    name: 'MACD Momentum Strategy',
    metrics: { winRate: '61.5', profitFactor: '1.78', sharpeRatio: '1.42', maxDrawdown: '14.1' }
  },
  {
    userMessage: "Mean reversion for QQQ. Buy when price drops 2 standard deviations below 20-day mean. Sell at the mean. Max 4% risk per trade with 8% stop loss.",
    claudeResponse: "I've created a Mean Reversion Strategy using Bollinger Band logic:",
    code: `# Mean Reversion Strategy
# Generated by Stratify AI

from stratify import Strategy

class MeanReversion(Strategy):
    def __init__(self):
        self.period = 20
        self.std_dev = 2.0
        self.position_size = 0.04
        self.stop_loss = 0.08

    def on_bar(self, bar):
        sma = self.indicators.SMA(self.period)
        std = self.indicators.STDDEV(self.period)
        lower_band = sma - (std * self.std_dev)

        if bar.close < lower_band and not self.position:
            self.buy(size=self.position_size)
            self.set_stop_loss(self.stop_loss)

        if self.position and bar.close >= sma:
            self.sell()`,
    name: 'Mean Reversion Strategy',
    metrics: { winRate: '71.2', profitFactor: '1.65', sharpeRatio: '1.93', maxDrawdown: '9.8' }
  }
];

export default function RightPanel({ width, alpacaData, theme, themeClasses, onStrategyGenerated, onDemoStateChange, onStrategyAdded, editingStrategy, onClearEdit }) {
  const [expanded, setExpanded] = useState(true);
  const [inputValue, setInputValue] = useState('');
  const [demoPhase, setDemoPhase] = useState('idle');
  const [displayedClaudeText, setDisplayedClaudeText] = useState('');
  const [displayedCode, setDisplayedCode] = useState('');
  const [userMessage, setUserMessage] = useState('');
  const [showUserMessage, setShowUserMessage] = useState(false);
  const [showClaudeResponse, setShowClaudeResponse] = useState(false);
  const [showAddButton, setShowAddButton] = useState(false);
  const [strategyIndex, setStrategyIndex] = useState(0);
  const messagesEndRef = useRef(null);

  const currentDemo = demoStrategies[strategyIndex];
  const currentStrategy = {
    id: Date.now() + strategyIndex,
    name: currentDemo.name,
    description: currentDemo.userMessage,
    code: currentDemo.code,
    status: 'draft',
    metrics: currentDemo.metrics
  };

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [displayedClaudeText, displayedCode, showClaudeResponse, showUserMessage, demoPhase]);

  // Handle editing an existing strategy
  useEffect(() => {
    if (editingStrategy) {
      setInputValue(editingStrategy.description || '');
      setDemoPhase('idle'); // Stop any demo
      setShowUserMessage(false);
      setShowClaudeResponse(false);
      setShowAddButton(false);
    }
  }, [editingStrategy]);

  // Start demo
  useEffect(() => {
    const timeout = setTimeout(() => {
      setDemoPhase('typing-user');
      if (onDemoStateChange) onDemoStateChange('thinking');
    }, 2000);
    return () => clearTimeout(timeout);
  }, []);

  // Typewriter for user input
  useEffect(() => {
    if (demoPhase !== 'typing-user') return;
    const message = currentDemo.userMessage;
    let index = 0;
    const interval = setInterval(() => {
      if (index <= message.length) {
        setInputValue(message.slice(0, index));
        index++;
      } else {
        clearInterval(interval);
        setTimeout(() => setDemoPhase('cursor-submit'), 600);
      }
    }, 40);
    return () => clearInterval(interval);
  }, [demoPhase, strategyIndex]);

  // Cursor to submit
  useEffect(() => {
    if (demoPhase !== 'cursor-submit') return;
    const clickTimeout = setTimeout(() => {
      setDemoPhase('clicking-submit');
      setTimeout(() => {
        setUserMessage(inputValue);
        setShowUserMessage(true);
        setInputValue('');
        setShowClaudeResponse(true);
        setDemoPhase('typing-claude');
      }, 400);
    }, 2000);
    return () => clearTimeout(clickTimeout);
  }, [demoPhase, inputValue]);

  // Typewriter for Claude response
  useEffect(() => {
    if (demoPhase !== 'typing-claude') return;
    const claudeResponse = currentDemo.claudeResponse;
    const code = currentDemo.code;
    let textIndex = 0;
    let codeIndex = 0;
    let typingCode = false;

    const interval = setInterval(() => {
      if (!typingCode && textIndex <= claudeResponse.length) {
        setDisplayedClaudeText(claudeResponse.slice(0, textIndex));
        textIndex++;
      } else if (!typingCode) {
        typingCode = true;
      } else if (codeIndex <= code.length) {
        setDisplayedCode(code.slice(0, codeIndex));
        codeIndex++;
      } else {
        clearInterval(interval);
        setTimeout(() => {
          setShowAddButton(true);
          setTimeout(() => setDemoPhase('cursor-add'), 500);
        }, 500);
      }
    }, 20);
    return () => clearInterval(interval);
  }, [demoPhase, strategyIndex]);

  // Cursor to add button
  useEffect(() => {
    if (demoPhase !== 'cursor-add') return;
    const clickTimeout = setTimeout(() => {
      setDemoPhase('clicking-add');
      setTimeout(() => {
        // Add strategy to center
        if (onStrategyGenerated) onStrategyGenerated(currentStrategy);
        setDemoPhase('complete');
        
        // Signal that strategy was added - trigger center panel animation
        setTimeout(() => {
          if (onStrategyAdded) onStrategyAdded(currentStrategy);
        }, 500);

      }, 400);
    }, 1500);
    return () => clearTimeout(clickTimeout);
  }, [demoPhase, strategyIndex]);

  // Reset for next cycle (triggered externally after deploy completes)
  const resetDemo = () => {
    setDemoPhase('idle');
    setInputValue('');
    setUserMessage('');
    setShowUserMessage(false);
    setDisplayedClaudeText('');
    setDisplayedCode('');
    setShowClaudeResponse(false);
    setShowAddButton(false);
    if (onDemoStateChange) onDemoStateChange('idle');
    setStrategyIndex(prev => (prev + 1) % demoStrategies.length);
    setTimeout(() => {
      setDemoPhase('typing-user');
      if (onDemoStateChange) onDemoStateChange('thinking');
    }, 2000);
  };

  // Expose resetDemo via window for Dashboard to call
  useEffect(() => {
    window.resetRightPanelDemo = resetDemo;
    return () => { delete window.resetRightPanelDemo; };
  }, [strategyIndex]);

  if (!expanded) {
    return (
      <div 
        className={`w-12 flex flex-col items-center py-4 gap-4 ${themeClasses.surfaceElevated} cursor-pointer transition-all duration-200 hover:bg-[#252525]`}
        onClick={() => setExpanded(true)}
      >
        <div className="flex flex-col items-center gap-1">
          <ClaudeIcon className="w-6 h-6" />
          <span className="text-[8px] text-gray-500">AI</span>
        </div>
        <div className="mt-auto">
          <svg className="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
        </div>
      </div>
    );
  }

  return (
    <div 
      className={`flex flex-col ${themeClasses.surfaceElevated} overflow-hidden transition-all duration-200`}
      style={{ width }}
    >
      {/* Header */}
      <div className={`flex items-center justify-between px-4 py-3 border-b ${themeClasses.border}`}>
        <div className="flex items-center gap-2">
          <ClaudeIcon className="w-5 h-5" />
          <span className={`text-sm font-semibold ${themeClasses.text}`}>AI Strategy Builder</span>
        </div>
        <button 
          onClick={() => setExpanded(false)}
          className="p-1 hover:bg-white/10 rounded transition-colors"
        >
          <svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
        </button>
      </div>

      {/* Messages Area */}
      <div className="flex-1 overflow-y-auto px-3 py-4 space-y-3 scrollbar-hide" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
        
        {/* User Message Bubble */}
        {showUserMessage && (
          <div className="flex justify-end animate-fadeIn">
            <div className="max-w-[85%] bg-blue-600 text-white rounded-2xl rounded-br-md px-4 py-2.5 text-sm">
              {userMessage}
            </div>
          </div>
        )}

        {/* Claude Response */}
        {showClaudeResponse && (
          <div className={`${themeClasses.surface} border ${themeClasses.border} rounded-lg p-3 animate-fadeIn`}>
            <div className="flex items-center gap-2 mb-2">
              <ClaudeIcon className="w-4 h-4" />
              <span className="text-[#f97316] text-xs font-semibold">Claude</span>
            </div>
            
            {displayedClaudeText && (
              <div className={`text-sm ${themeClasses.text} mb-2`}>
                {displayedClaudeText}
                {demoPhase === 'typing-claude' && !displayedCode && <span className="animate-pulse text-[#f97316]">|</span>}
              </div>
            )}
            
            {displayedCode && (
              <div className="mt-3 space-y-3">
                <div className={`${themeClasses.bg} rounded-lg p-3 border ${themeClasses.border}`}>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs text-gray-500">Generated Code</span>
                    <button className="text-xs text-purple-400 hover:text-purple-300">Edit</button>
                  </div>
                  <pre className="text-xs text-gray-400 overflow-x-auto font-mono leading-relaxed whitespace-pre-wrap scrollbar-hide" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
                    {displayedCode}
                    {demoPhase === 'typing-claude' && <span className="animate-pulse text-[#f97316]">|</span>}
                  </pre>
                </div>

                {/* Add to Strategies Button */}
                {showAddButton && (
                  <div className="flex justify-center pt-2 relative">
                    <button 
                      className={`relative px-4 py-2 text-sm font-medium rounded-lg transition-all flex items-center gap-2 ${
                        demoPhase === 'clicking-add' 
                          ? 'bg-emerald-500 text-white scale-95' 
                          : demoPhase === 'complete'
                          ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/50'
                          : 'bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 border border-emerald-500/30'
                      }`}
                    >
                      {demoPhase === 'complete' ? (
                        <>
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                          </svg>
                          Added to Strategies
                        </>
                      ) : (
                        <>
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                          </svg>
                          Add to Strategies
                        </>
                      )}
                    </button>
                    <AnimatedCursor phase={demoPhase} target="add" />
                  </div>
                )}
              </div>
            )}
          </div>
        )}
        
        <div ref={messagesEndRef} />
      </div>

      {/* Input Area */}
      <div className={`border-t ${themeClasses.border} p-3 ${themeClasses.surfaceElevated} relative`}>
        <div className="relative">
          <textarea
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            placeholder="Describe your trading strategy..."
            rows={3}
            className={`w-full px-3 py-2 ${themeClasses.surface} border ${themeClasses.border} focus:border-[#f97316] rounded-lg text-sm ${themeClasses.text} placeholder-gray-600 focus:outline-none transition-colors resize-none`}
            readOnly={demoPhase === 'typing-user' || demoPhase === 'cursor-submit'}
          />
          <div className="relative">
            <button
              disabled={!inputValue.trim()}
              className={`absolute right-2 bottom-2 p-1 transition-all ${
                demoPhase === 'clicking-submit'
                  ? 'text-orange-300 scale-90'
                  : 'text-gray-400 hover:text-white disabled:text-gray-600 disabled:cursor-not-allowed'
              }`}
            >
              <svg 
                className={`w-5 h-5 transition-transform duration-200 ${
                  demoPhase === 'clicking-submit' ? 'rotate-180' : ''
                }`} 
                fill="none" 
                stroke="currentColor" 
                viewBox="0 0 24 24"
              >
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
              </svg>
            </button>
            {(demoPhase === 'cursor-submit' || demoPhase === 'clicking-submit') && (
              <AnimatedCursor phase={demoPhase} target="submit" />
            )}
          </div>
        </div>
        <div className="flex items-center gap-2 mt-2 text-xs text-gray-500">
          <span>Enter to send</span>
          <span>•</span>
          <span>Shift+Enter for new line</span>
        </div>
      </div>

      <style>{`
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(5px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fadeIn {
          animation: fadeIn 0.3s ease-out forwards;
        }
      `}</style>
    </div>
  );
}
