import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { WebSocketServer } from 'ws';
import YahooFinance from 'yahoo-finance2';
import OpenAI from 'openai';
import stocksRouter from './routes/stocks.js';
import chatRouter from './routes/chat.js';
import kalshiRouter from './routes/kalshi.js';
import { startAlpacaStream } from './services/alpaca.js';

dotenv.config();

// Initialize OpenAI
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// Initialize Yahoo Finance
const yahooFinance = new YahooFinance();

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

app.use('/api/stocks', stocksRouter);
app.use('/api/v1/kalshi', kalshiRouter);
app.use('/api/claude', chatRouter);

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Atlas AI Chat Endpoint
app.post('/api/v1/chat/', async (req, res) => {
  try {
    const { message, strategy_name } = req.body;
    
    if (!message) {
      return res.status(400).json({ error: 'Message is required' });
    }

    const strategyName = strategy_name || `Strategy_${Date.now() % 10000}`;
    const className = strategyName.replace(/[^a-zA-Z0-9]/g, '');

    const systemPrompt = `You are Atlas, an AI assistant for Stratify - a trading strategy platform. 
Your job is to convert natural language trading strategy descriptions into Python code.

When generating strategy code:
1. Use the Stratify framework syntax
2. Include proper class structure with __init__ and on_bar methods
3. Use self.indicators for technical indicators (RSI, SMA, EMA, MACD, ATR, etc.)
4. Use self.buy() and self.sell() for trade execution
5. Include position sizing and risk management when mentioned
6. Add helpful comments

Always respond with a brief explanation followed by the code block.
The code should be practical and executable.`;

    const userPrompt = `Create a trading strategy called "${strategyName}" based on this description:

${message}

Generate the Python code for this strategy using the Stratify framework.`;

    const completion = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      temperature: 0.7,
      max_tokens: 1500,
    });

    const aiResponse = completion.choices[0].message.content;
    
    // Extract code block if present
    const codeMatch = aiResponse.match(/```python\n([\s\S]*?)```/) || 
                      aiResponse.match(/```\n([\s\S]*?)```/);
    
    let code = codeMatch ? codeMatch[1].trim() : null;
    
    // If no code block found, generate a basic template
    if (!code) {
      code = `# ${strategyName}
# Generated by Atlas AI

from stratify import Strategy

class ${className}(Strategy):
    def __init__(self):
        self.position_size = 0.02
        self.stop_loss = 0.05

    def on_bar(self, bar):
        # Strategy logic based on: ${message}
        pass`;
    }

    // Extract explanation (text before code block)
    const explanationMatch = aiResponse.split('```')[0].trim();
    const response = explanationMatch || `I've created a ${strategyName} based on your description:`;

    res.json({
      response,
      code,
      strategy_name: strategyName,
    });

  } catch (error) {
    console.error('Atlas AI error:', error);
    
    // Check if it's an API key issue
    if (error.code === 'invalid_api_key' || error.status === 401) {
      return res.status(500).json({ 
        error: 'OpenAI API key not configured',
        details: 'Please add OPENAI_API_KEY to your environment variables'
      });
    }
    
    res.status(500).json({ 
      error: 'Failed to generate strategy',
      details: error.message 
    });
  }
});

// Grok AI Chat Endpoint
app.post('/api/atlas/chat', async (req, res) => {
  try {
    const { message } = req.body;
    if (!message) return res.status(400).json({ error: 'Message is required' });

    const GROK_API_KEY = process.env.GROK_API_KEY;
    if (!GROK_API_KEY) return res.status(500).json({ error: 'Grok API key not configured' });

    const response = await fetch('https://api.x.ai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${GROK_API_KEY}`
      },
      body: JSON.stringify({
        model: 'grok-3',
        messages: [
          { role: 'system', content: 'You are Grok, a trading strategy AI for Stratify. Be concise. When generating code, use Alpaca API for data and backtesting (alpaca-trade-api package), NOT yfinance. Provide only working Python code with minimal comments. No lengthy explanations.' },
          { role: 'user', content: message }
        ],
        temperature: 0.7,
        max_tokens: 2048,
      }),
    });

    if (!response.ok) return res.status(response.status).json({ error: 'Grok API error' });

    const data = await response.json();
    res.json({ response: data.choices?.[0]?.message?.content || 'No response' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

const server = app.listen(PORT, () => {
  console.log(`🚀 Stratify API running on http://localhost:${PORT}`);
});

const wss = new WebSocketServer({ server });

wss.on('connection', (ws) => {
  console.log('Client connected to WebSocket');
  ws.on('close', () => console.log('Client disconnected'));
});

startAlpacaStream((data) => {
  wss.clients.forEach((client) => {
    if (client.readyState === 1) {
      client.send(JSON.stringify(data));
    }
  });
});

// Yahoo Finance API endpoints (Google Finance style data)
app.get('/api/public/quote/:symbol', async (req, res) => {
  try {
    const { symbol } = req.params;
    const sym = symbol.toUpperCase();
    
    const quote = await yahooFinance.quote(sym);
    
    res.json({ 
      symbol: sym,
      name: quote.shortName || quote.longName || sym,
      price: quote.regularMarketPrice || 0,
      change: quote.regularMarketChange || 0,
      changePercent: quote.regularMarketChangePercent || 0,
      prevClose: quote.regularMarketPreviousClose || 0,
      open: quote.regularMarketOpen || 0,
      dayHigh: quote.regularMarketDayHigh || 0,
      dayLow: quote.regularMarketDayLow || 0,
      volume: quote.regularMarketVolume || 0,
      avgVolume: quote.averageDailyVolume3Month || 0,
      marketCap: quote.marketCap || 0,
      fiftyTwoWeekHigh: quote.fiftyTwoWeekHigh || 0,
      fiftyTwoWeekLow: quote.fiftyTwoWeekLow || 0,
      exchange: quote.exchange || '',
      currency: quote.currency || 'USD',
      marketState: quote.marketState || 'CLOSED',
      // Pre/Post market data
      preMarketPrice: quote.preMarketPrice,
      preMarketChange: quote.preMarketChange,
      preMarketChangePercent: quote.preMarketChangePercent,
      postMarketPrice: quote.postMarketPrice,
      postMarketChange: quote.postMarketChange,
      postMarketChangePercent: quote.postMarketChangePercent,
    });
  } catch (error) {
    console.error('Yahoo Finance error:', error.message);
    res.status(500).json({ error: error.message });
  }
});

// Get historical data for charts
app.get('/api/public/history/:symbol', async (req, res) => {
  try {
    const { symbol } = req.params;
    const { period = '1d', interval = '5m' } = req.query;
    const sym = symbol.toUpperCase();
    
    const result = await yahooFinance.chart(sym, {
      period1: getPeriodStart(period),
      interval: interval,
    });
    
    const data = result.quotes.map(q => ({
      time: q.date,
      open: q.open,
      high: q.high,
      low: q.low,
      close: q.close,
      volume: q.volume,
    }));
    
    res.json({
      symbol: sym,
      period,
      interval,
      data,
    });
  } catch (error) {
    console.error('Yahoo Finance history error:', error.message);
    res.status(500).json({ error: error.message });
  }
});

// Helper function for period calculation
function getPeriodStart(period) {
  const now = new Date();
  switch(period) {
    case '1d': return new Date(now.setDate(now.getDate() - 1));
    case '5d': return new Date(now.setDate(now.getDate() - 5));
    case '1mo': return new Date(now.setMonth(now.getMonth() - 1));
    case '3mo': return new Date(now.setMonth(now.getMonth() - 3));
    case '6mo': return new Date(now.setMonth(now.getMonth() - 6));
    case '1y': return new Date(now.setFullYear(now.getFullYear() - 1));
    case '5y': return new Date(now.setFullYear(now.getFullYear() - 5));
    default: return new Date(now.setDate(now.getDate() - 1));
  }
}

// Search using Yahoo Finance
app.get('/api/public/search', async (req, res) => {
  try {
    const { q } = req.query;
    if (!q || q.length < 1) {
      return res.json([]);
    }
    
    const results = await yahooFinance.search(q);
    
    const stocks = (results.quotes || [])
      .filter(r => r.quoteType === 'EQUITY' || r.quoteType === 'ETF')
      .slice(0, 15)
      .map(r => ({
        symbol: r.symbol,
        name: r.shortname || r.longname || r.symbol,
        exchange: r.exchange,
        type: r.quoteType,
      }));
    
    res.json(stocks);
  } catch (error) {
    console.error('Yahoo Finance search error:', error.message);
    res.status(500).json({ error: error.message });
  }
});

// Trending/popular stocks
app.get('/api/public/trending', async (req, res) => {
  try {
    const trending = await yahooFinance.trendingSymbols('US');
    const symbols = trending.quotes.slice(0, 10).map(q => q.symbol);
    
    const quotes = await Promise.all(
      symbols.map(async (sym) => {
        try {
          const quote = await yahooFinance.quote(sym);
          return {
            symbol: sym,
            name: quote.shortName || sym,
            price: quote.regularMarketPrice,
            changePercent: quote.regularMarketChangePercent,
          };
        } catch {
          return null;
        }
      })
    );
    
    res.json(quotes.filter(q => q !== null));
  } catch (error) {
    console.error('Yahoo Finance trending error:', error.message);
    res.status(500).json({ error: error.message });
  }
});
